class_name CompiInstance
## An instance of a Concept.
##
## Instances are used by TMRs,
## short and long term memory.[br]
## Instances are actualizations of Concepts.
## For example there is the concept "Apple",
## and also is the particular instance of "Apple"
## I'm eating right now. They are usually
## generated by lexeme's moves.
